# Generated by Django 5.0.3 on 2024-03-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("StudentHubApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="students",
            name="studentId",
            field=models.IntegerField(),
        ),
    ]
