# Generated by Django 5.0.3 on 2024-03-14 15:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("StudentHubApp", "0002_alter_students_studentid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="courses",
            old_name="Capacity",
            new_name="capacity",
        ),
    ]
