# Generated by Django 5.0.3 on 2024-03-14 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "StudentHubApp",
            "0004_students_courseenrolled_alter_courses_coursename_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="students",
            name="courseEnrolled",
            field=models.ForeignKey(
                default="Master of Computing",
                on_delete=django.db.models.deletion.CASCADE,
                to="StudentHubApp.courses",
            ),
        ),
    ]
