# Generated by Django 5.0.3 on 2024-03-14 17:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("StudentHubApp", "0005_alter_students_courseenrolled"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="students",
            name="courseEnrolled",
        ),
    ]
